'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase-client'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Tenda } from '@/types/database'
import styles from './register.module.css'

export default function RegisterPage() {
    const [tendas, setTendas] = useState<Tenda[]>([])
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [formData, setFormData] = useState({
        email: '',
        password: '',
        name: '',
        surname: '',
        cpf: '',
        phone: '',
        church_years: '',
        is_baptized: false,
        tenda_id: '',
        birth_date: '',
        sex: 'Masculino',
    })

    const supabase = createClient()
    const router = useRouter()

    useEffect(() => {
        async function fetchTendas() {
            const { data } = await supabase.from('tendas').select('*')
            if (data) setTendas(data)
        }
        fetchTendas()
    }, [])

    const maskCPF = (value: string) => {
        return value
            .replace(/\D/g, '')
            .replace(/(\d{3})(\d)/, '$1.$2')
            .replace(/(\d{3})(\d)/, '$1.$2')
            .replace(/(\d{3})(\d{1,2})/, '$1-$2')
            .replace(/(-\d{2})\d+?$/, '$1')
    }

    const maskPhone = (value: string) => {
        return value
            .replace(/\D/g, '')
            .replace(/(\d{2})(\d)/, '($1) $2')
            .replace(/(\d{5})(\d)/, '$1-$2')
            .replace(/(-\d{4})\d+?$/, '$1')
    }

    const handleRegister = async (e: React.FormEvent) => {
        e.preventDefault()
        setLoading(true)
        setError(null)

        try {
            const cleanCpf = formData.cpf.replace(/\D/g, '')
            const cleanPhone = formData.phone.replace(/\D/g, '')

            if (cleanCpf.length !== 11) {
                throw new Error('CPF deve ter 11 dígitos.')
            }

            // Sign up user with data in metadata
            const { data: authData, error: authError } = await supabase.auth.signUp({
                email: formData.email,
                password: formData.password,
                options: {
                    data: {
                        name: formData.name,
                        surname: formData.surname,
                        cpf: cleanCpf,
                        phone: cleanPhone,
                        church_years: formData.church_years,
                        is_baptized: formData.is_baptized,
                        tenda_id: formData.tenda_id,
                        birth_date: formData.birth_date,
                        sex: formData.sex,
                        // Matricula is now generated by DB sequence automatically
                    }
                }
            })

            if (authError) throw authError
            if (!authData.user) throw new Error('Falha no cadastro.')

            // Profile is created by DB Trigger!
            router.push('/login?registered=true')
        } catch (err: any) {
            if (err.message.includes('rate limit')) {
                setError('Limite de envio de e-mail atingido. Desative o "Confirm email" no painel do Supabase.')
            } else {
                setError(err.message)
            }
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className={styles.container}>
            <h1 className={styles.title}>Cadastro SEBAP</h1>

            <form className={styles.form} onSubmit={handleRegister}>
                {error && <div className={styles.errorMessage}>{error}</div>}

                <div className={styles.grid}>
                    <div className={styles.inputGroup}>
                        <label>Nome</label>
                        <input
                            type="text"
                            required
                            value={formData.name}
                            onChange={e => setFormData({ ...formData, name: e.target.value })}
                            placeholder="Ex: João"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Sobrenome</label>
                        <input
                            type="text"
                            required
                            value={formData.surname}
                            onChange={e => setFormData({ ...formData, surname: e.target.value })}
                            placeholder="Ex: Silva"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>E-mail</label>
                        <input
                            type="email"
                            required
                            value={formData.email}
                            onChange={e => setFormData({ ...formData, email: e.target.value })}
                            placeholder="seu@email.com"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Senha</label>
                        <input
                            type="password"
                            required
                            value={formData.password}
                            onChange={e => setFormData({ ...formData, password: e.target.value })}
                            placeholder="********"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>CPF</label>
                        <input
                            type="text"
                            required
                            value={formData.cpf}
                            onChange={e => setFormData({ ...formData, cpf: maskCPF(e.target.value) })}
                            placeholder="000.000.000-00"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Telefone</label>
                        <input
                            type="tel"
                            value={formData.phone}
                            onChange={e => setFormData({ ...formData, phone: maskPhone(e.target.value) })}
                            placeholder="(00) 00000-0000"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Qual tenda você pertence?</label>
                        <select
                            required
                            value={formData.tenda_id}
                            onChange={e => setFormData({ ...formData, tenda_id: e.target.value })}
                        >
                            <option value="">Selecione uma tenda</option>
                            {tendas.map(tenda => (
                                <option key={tenda.id} value={tenda.id}>{tenda.name}</option>
                            ))}
                        </select>
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Ano de igreja (tempo)</label>
                        <input
                            type="number"
                            value={formData.church_years}
                            onChange={e => setFormData({ ...formData, church_years: e.target.value })}
                            placeholder="Ex: 5"
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Data de Nascimento</label>
                        <input
                            type="date"
                            required
                            value={formData.birth_date}
                            onChange={e => setFormData({ ...formData, birth_date: e.target.value })}
                        />
                    </div>

                    <div className={styles.inputGroup}>
                        <label>Sexo</label>
                        <select
                            value={formData.sex}
                            onChange={e => setFormData({ ...formData, sex: e.target.value })}
                        >
                            <option value="Masculino">Masculino</option>
                            <option value="Feminino">Feminino</option>
                        </select>
                    </div>
                </div>

                <div className={styles.checkboxGroup}>
                    <input
                        type="checkbox"
                        id="is_baptized"
                        checked={formData.is_baptized}
                        onChange={e => setFormData({ ...formData, is_baptized: e.target.checked })}
                    />
                    <label htmlFor="is_baptized">Já é batizado?</label>
                </div>

                <button type="submit" disabled={loading} className={styles.submitBtn}>
                    {loading ? 'Cadastrando...' : 'Finalizar Cadastro'}
                </button>

                <p className={styles.loginLink}>
                    Já tem conta? <Link href="/login">Voltar para o Login</Link>
                </p>
            </form>
        </div>
    )
}
